#########################################################################################################
################################## IN GROUPE COPYRIGHT  #################################################
stages:  
  - build_and_deploy

variables:
  MAVEN_GROUPEID: com.ingroupe.efti
  MAVEN_ARTIFACTID: efti-gate
  MAVEN_EXTENSION: jar
  VERSION_ARTEFACT_SNAPSHOT: 0.2.0-SNAPSHOT
  VERSION_ARTEFACT_RELEASE: 0.1.0
  DEPLOY_ENVIRONMENT:
    value: "dev"
    options:
      - "dev"
      - "int"
    description: "The deployment target. Set to 'dev' by default."
  REBUILD_COMPONENT_IMAGE:
    value: "true"
    options:
      - "true"
      - "false"
    description: "Allow to rebuild or no the component Image. Set to 'true' by default."

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "web" && $DEPLOY_ENVIRONMENT == "dev"
      variables:
        NAMESPACE_DEV: app-dev-efti
        CONTEXT: dev-efti
    - if: $CI_PIPELINE_SOURCE == "api" || $CI_PIPELINE_SOURCE == "web" && $DEPLOY_ENVIRONMENT == "int"
      variables:
        NAMESPACE: app-int-efti
        CONTEXT: int-efti
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_REF_NAME !~ "develop"
      when: never
    - when: always

build_and_deploy_microservice:
  stage: build_and_deploy
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /feat/
      variables:
        TAG: PREVIEW
      when: manual
    - when: always
  trigger:
    include:
      - project: "kube/build"
        file: "build_ms.yml"
        ref: "kustomize"
    forward:
      pipeline_variables: true
    strategy: depend