spring:
  application:
    name: efti-gate
  datasource:
    url: jdbc:postgresql://localhost:9000/efti
    username: ingroup
    password: root
    driverClassName: org.postgresql.Driver

server:
  port: 9001
