spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.borduria.eu:8080/realms/eFTI_BO
  jpa:
    properties:
      hibernate:
        default_schema: "eftibo"

gate:
  owner: borduria
  ap:
    url: http://efti.gate.borduria.eu:81/domibus/services/wsplugin
    username: borduria_service_account
    password: Azerty59*1234567

