server:
  port: 8072

gate:
  owner: http://efti.platform.umbrellainc.com
  cda_path: ./cda/
  gate: http://efti.gate.listenbourg.eu
  ap:
    url: http://efti.platform.umbrellainc.com:81/domibus/services/wsplugin
    username: umbrellacorporation_service_account
    password: Azerty59*1234567

