spring:
  application:
    name: efti-gate
  datasource:
    control:
      jdbc-url: jdbc:postgresql://localhost:9000/efti
      url: jdbc:postgresql://localhost:9000/efti
      username: ingroup
      password: root
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.gate.changelog-master.xml
    metadata:
      jdbc-url: jdbc:postgresql://localhost:2345/efti
      url: jdbc:postgresql://localhost:2345/efti
      username: root
      password: root
      driverClassName: org.postgresql.Driver
      liquibase:
        change-log: classpath:db.changelog/db.metadata.changelog-master.xml
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8880

batch:
  retry:
    cron: "*/20 * * * * *"
    time: 20, 120, 300
    size: 10

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
