spring:
  application:
    name: efti-platform
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always

server:
  port: 8070

gate:
  cda_path: C:\projet\EFTI\platform-gate-simulator\src\main\resources\cda\
  owner: http://efti.platform.acme.com
  gate: http://efti.gate.borduria.eu
  ap:
    url: http://efti.platform.acme.com:81/domibus/services/wsplugin
    username: acme_service_account
    password: Azerty59*1234567

