spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.gate.syldavia.eu:8080/realms/eFTI_SY
  jpa:
    properties:
      hibernate:
        default_schema: "eftisy"
  #----- Liquibase -----#
  liquibase:
    enabled: true
    defaultSchema: eftisy
    parameters:
      defaultSchema: ${spring.liquibase.defaultSchema}
    change-log: classpath:db/changelog/db.changelog-master.xml
gate:
  owner: syldavia
  ap:
    url: http://efti.gate.syldavia.eu:81/domibus/services/wsplugin
    username: syldavia_service_account
    password: Azerty59*1234567
