server:
  port: 8071

gate:
  minSleep: 1000
  maxSleep: 2000
  owner: http://efti.platform.massivedynamic.com
  cda_path: ./cda/
  gate: http://efti.gate.syldavia.eu
  ap:
    url: http://efti.platform.massivedynamic.com:81/domibus/services/wsplugin
    username: massivedynamic_service_account
    password: Azerty59*1234567

