spring:
  application:
    name: efti-gate
  datasource:
    url: jdbc:postgresql://localhost:9000/efti
    username: ingroup
    password: root
    driverClassName: org.postgresql.Driver

server:
  port: 9001


batch:
  retry:
    cron: "*/20 * * * * *"
    time: 20, 120, 300
    size: 10

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
