spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/eFTI_BO
  jpa:
    properties:
      hibernate:
        default_schema: "eftibo"

