openapi: 3.0.3
info:
  title: eFTI Platform API
  description: API that eFTI Platforms implement to communicate with the eFTI Gate
  version: 0.5.0
paths:
  /api/v0/consignments/{datasetId}:
    get:
      summary: Return the consignment with the given datasetId
      description: >
        Gate delegates requests from Competent Authorities to the appropriate Platform
        and calls this endpoint to retrieve the consignment with the given datasetId
      parameters:
        - name: datasetId
          in: path
          description: The datasetId of the consignment to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Consignment found
          content:
            application/xml:
              schema:
                type: object
                description: Consignment in XML format following the eFTI schema `http://efti.eu/v1/consignment/common`
